### ISSUE TITLE
Add support for Notion-Version 2022-06-28

### ISSUE THREAD

**Issue by KoditkarVedant** [notion-dotnet/notion-sdk-net#257]
Notion has released Notion-Version 2022-06-28 with the following backwards incompatible changes:

- [x] #298
- [x] #258
- [x] #259
- [x] #260

**Notion changelog:** https://developers.notion.com/changelog/releasing-notion-version-2022-06-28

**Comment by KoditkarVedant** [comment]
I have released the preview version. The final release version is set out to be published by 28th or 31st August 2022.

**Comment by Scantheus** [comment]
Notion reversed themselves and put support for property values and types back into queries for the 2022-06-28 version.

https://developers.notion.com/changelog

That page properties end point change they did was terrible. My testing on Notion.Net v4 preview had a query that returned 28 records with 6 text properties go from <400ms to >32000 because if the requirement to call RetrievePagePropertyItem for every property.

**Comment by KoditkarVedant** [comment]
4.0.0 Released
